### ISSUE TITLE
Document code

### ISSUE THREAD

**Issue by Frazzot** [itggot-edvin-alestig/gymnasiearbete#51]
Document the code, no particular standard but comment classes and functions by the following example. 

```
// Description of class/function
// Args:
// Datatype : Argument 1 name : Description of argument 1 
// Datatype : Argument 2 name : Description of argument 2
```

Other comments in the code to clarify obscure code should also be included.

**Comment by itggot-edvin-alestig** [comment]
Done, see #58.
