### ISSUE TITLE
Change route when "Give Up"

### ISSUE THREAD

**Issue by Frazzot** [itggot-edvin-alestig/gymnasiearbete#54]
Create the page of "player x won!" and change to that route when the give up button is clicked.

**Comment by Frazzot** [comment]
Current state: The Ending page shows up when button is clicked, left is to fix the html to show the correct player.

**Comment by itggot-edvin-alestig** [comment]
I think the scores should be displayed as well as the winner.

**Comment by Frazzot** [comment]
Solved it with a XMLHttpRequest.
