### ISSUE TITLE
Question about the letters class

### ISSUE THREAD

**Issue by itggot-edvin-alestig** [itggot-edvin-alestig/gymnasiearbete#9]
Is it better to use a Letter object for the individual letters?
It would contain the letter and the points for the letter. Currently it uses the letters as strings and there is a method for retrieving the points for that letter. The blank letter is already a class of its own so it might be beneficial to treat all letters as objects. The blank letter could then inherit from the main letter class.

**Comment by Frazzot** [comment]
Primarily, we will go for the option to keep the letters as strings, as we believe it will be easier to use.
